Add missing include for flatpak-integrator plugin
flatpak-integrator/plugin.cpp:160:13: error: use of undeclared identifier 'close'
  160 |             close(dirfd);
      |             ^